name: Create New Tag

on:
  workflow_run:
    workflows: 
      - "mongodump"
    types: 
      - completed

jobs:
  build_master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: tags
        id: tag
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e "s/refs\/tags\///")"
          echo "::set-output name=tag::$TAG"

  build_other_branches:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the Branch name
        id: tag
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e "s/refs\/tags\///")"
          echo "::set-output name=tag::$TAG"
