name: Create New Tag

on:
  workflow_run:
    workflows: 
      - "mongodump"
    types: 
      - completed

jobs:
  build_master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

  build_other_branches:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Get the Branch name
        id: tag
        run: |
          TAG=$"(echo "${{ steps.meta.outputs.tags }}")"
          echo "::set-output name=tag::${TAG}"
